// import { contextBridge, ipcRenderer } from "electron"; // es6
const { contextBridge, ipcRenderer } = require("electron"); // CommonJS
contextBridge.exposeInMainWorld("ElectronAPI", {
  Product: {
    get: (data) => ipcRenderer.invoke("getProduct", data),
    pagination: (data) => ipcRenderer.invoke("paginationProduct", data),
    getStock: (data) => ipcRenderer.invoke("getProductStock", data),
    pagination1: (data) => ipcRenderer.invoke("paginationProduct1", data),
    create: (data) => ipcRenderer.invoke("createProduct", data),
    delete: (data) => ipcRenderer.invoke("deleteProduct", data),
    update: (data) => ipcRenderer.invoke("updateProduct", data),
    csv: () => ipcRenderer.invoke("getProductCSV"),
    pdf: () => ipcRenderer.invoke("getProductPDF"),
    list: () => ipcRenderer.invoke("getProductList"),
  },
  User: {
    get: (data) => ipcRenderer.invoke("getUser", data),
    pagination: (data) => ipcRenderer.invoke("paginationUser", data),
    supplier: () => ipcRenderer.invoke("getSupplier"),
    register: (data) => ipcRenderer.invoke("registerUser", data),
    delete: (data) => ipcRenderer.invoke("deleteUser", data),
    update: (data) => ipcRenderer.invoke("updateUser", data),
    investor: () => ipcRenderer.invoke("getInvestor"),
    list: () => ipcRenderer.invoke("getUserList"),
    sale: () => ipcRenderer.invoke("getSales"),
    customer: () => ipcRenderer.invoke("getCustomer"),
    creditor: () => ipcRenderer.invoke("getCreditor"),
    receivable: () => ipcRenderer.invoke("getReceivable"),
  },
  Stock: {
    get: (data) => ipcRenderer.invoke("getStock", data),
    pagination: (data) => ipcRenderer.invoke("getStockPagination", data),
    csv: (data) => ipcRenderer.invoke("getStockCSV", data),
    pdf: (data) => ipcRenderer.invoke("getStockPDF", data),
    get1: (data) => ipcRenderer.invoke("getStock1", data),
    pagination1: (data) => ipcRenderer.invoke("getStockPagination1", data),
    csv1: (data) => ipcRenderer.invoke("getStockCSV1", data),
    pdf1: (data) => ipcRenderer.invoke("getStockPDF1", data),
  },
  Accounting: {
    pagination: (data) => ipcRenderer.invoke("paginationAccounting", data),
    get: (data) => ipcRenderer.invoke("getAccounting", data),
    asset: (data) => ipcRenderer.invoke("getAsset", data),
    cash: () => ipcRenderer.invoke("getCash"),
    financialStatement: () => ipcRenderer.invoke("financialStatement"),
    csv: (data) => ipcRenderer.invoke("getAccountingCSV", data),
    pdf: (data) => ipcRenderer.invoke("getAccountingPDF", data),
    pdf1: (data) => ipcRenderer.invoke("getAccountingPDF1", data),
    pdf2: (data) => ipcRenderer.invoke("getAccountingPDF2", data),
    pdf3: (data) => ipcRenderer.invoke("getAccountingPDF3", data),
    pdf4: (data) => ipcRenderer.invoke("getAccountingPDF4", data),
    pdf5: (data) => ipcRenderer.invoke("getAccountingPDF5", data),
    pdf6: (data) => ipcRenderer.invoke("getAccountingPDF6", data),
    pdf7: (data) => ipcRenderer.invoke("getAccountingPDF7", data),
    pdf8: (data) => ipcRenderer.invoke("getAccountingPDF8", data),
    create: (data) => ipcRenderer.invoke("createAccounting", data),
    create1: (data) => ipcRenderer.invoke("createAccounting1", data),
    create2: (data) => ipcRenderer.invoke("createAccounting2", data),
    create3: (data) => ipcRenderer.invoke("createAccounting3", data),
    create4: (data) => ipcRenderer.invoke("createAccounting4", data),
    create5: (data) => ipcRenderer.invoke("createAccounting5", data),
    create6: (data) => ipcRenderer.invoke("createAccounting6", data),
    create7: (data) => ipcRenderer.invoke("createAccounting7", data),
    create8: (data) => ipcRenderer.invoke("createAccounting8", data),
    create9: (data) => ipcRenderer.invoke("createAccounting9", data),
    create10: (data) => ipcRenderer.invoke("createAccounting10", data),
    create11: (data) => ipcRenderer.invoke("createAccounting11", data),
    create12: (data) => ipcRenderer.invoke("createAccounting12", data),
    create13: (data) => ipcRenderer.invoke("createAccounting13", data),
    create14: (data) => ipcRenderer.invoke("createAccounting14", data),
    create15: (data) => ipcRenderer.invoke("createAccounting15", data),
    create16: (data) => ipcRenderer.invoke("createAccounting16", data),
    create17: (data) => ipcRenderer.invoke("createAccounting17", data),
    create18: (data) => ipcRenderer.invoke("createAccounting18", data),
    create19: (data) => ipcRenderer.invoke("createAccounting19", data),
    create20: (data) => ipcRenderer.invoke("createAccounting20", data),
    create21: (data) => ipcRenderer.invoke("createAccounting21", data),
  },
  saveCSV: (data) => ipcRenderer.invoke("save-csv", data),
  savePDF: (htmlContent) => ipcRenderer.invoke("generate-pdf", htmlContent),
  navigateTo: (file) => ipcRenderer.send("navigate", file),
  logout: () => ipcRenderer.send("logout-apps"),
  close: () => ipcRenderer.send("close-apps"),
  minimize: () => ipcRenderer.send("minimize-apps"),
  restore: () => ipcRenderer.send("restore-apps"),
});
